# this is a sample config file - for testing only

# input data configs
samples: metadata/samples_small.csv

# output configs
output_dir: output_subsampler

# execution config
coverages: # to which coverages you want to subsample?
  - 5
  - 10

technologies:
  - nanopore
  - illumina

strategies:
  - filter  # filtlong
  - random  # rasusa

mean_q_weight: 10  # filtlong param
min_length: 150    # filtlong param
seed: 42           # filtlong and rasusa param

container: docker://leandroishilima/subsampler:pandora_paper_tag1
